name: Environment Example

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: production

    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          echo "Building and testing the code..."

      - name: Deploy to server
        run: |
          echo "Deploying to ${{ env.DEPLOYMENT_ENV }} environment..."
          # Deployment steps go here

      - name: Send notifications
        run: |
          echo "Sending notifications..."
          # Notification steps go here
