name: Environment Example

on:
  push:
    branches:
      - main

env:
  DEPLOYMENT_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ env.DEPLOYMENT_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          echo "Building and testing the code..."

      - name: Deploy to server
        run: |
          echo "Deploying to ${{ env.DEPLOYMENT_ENV }} environment..."
          # Deployment steps go here

      - name: Send notifications
        run: |
          echo "Sending notifications..."
          # Notification steps go here
